In [4]:
import numpy as np
import pandas as pd
import sklearn 


from pandas import Series,DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [6]:
from sklearn.linear_model import Perceptron

In [8]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [9]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [11]:
standardize = StandardScaler()
standardized_X_test = standardize.fit_transform(X_test)
standardized_X_train = standardize.fit_transform(X_train)

In [12]:
standardized_X_test[0:10]

array([[-1.50699304,  0.21948312, -1.3571399 , -1.44391201],
       [ 0.2962465 ,  0.0070801 ,  0.63628518,  0.72874556],
       [ 0.2962465 , -1.69214407,  0.75709882,  0.32137227],
       [ 0.16744367,  0.0070801 ,  0.27384425,  0.32137227],
       [-0.2189648 , -0.41772594,  0.696692  ,  1.00032775],
       [-1.50699304,  1.28149823, -1.659174  , -1.44391201],
       [ 0.03864085, -0.84253198,  0.15303061, -0.08600103],
       [ 1.45547192,  0.21948312,  0.9987261 ,  1.13611885],
       [ 1.19786627,  0.0070801 ,  0.87791246,  1.40770105],
       [ 0.81145779, -0.41772594,  1.11953974,  1.27190995]])

In [13]:
perceptron = Perceptron(max_iter=50 , eta0=0.15, tol=1e-3,random_state=15)

perceptron.fit(standardized_X_train,y_train.ravel())

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.15,
           fit_intercept=True, max_iter=50, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=15, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [14]:
y_pred = perceptron.predict(standardized_X_test)

print(y_test)

[0 2 2 1 2 0 1 2 2 2 0 0 0 1 0 2 1 1 2 2 0 2 1 1 0 1 0 1 2 1]


In [15]:
print(y_pred)

[0 2 1 0 2 0 1 2 2 2 1 0 0 1 0 2 1 1 1 2 0 2 1 1 0 1 0 0 2 1]


In [16]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.89      0.84         9
           1       0.73      0.80      0.76        10
           2       1.00      0.82      0.90        11

    accuracy                           0.83        30
   macro avg       0.84      0.84      0.83        30
weighted avg       0.85      0.83      0.84        30

